services:
  # php:
  #   build: ./php-fpm
  #   container_name: php_fpm
  #   volumes:
  #     - ../sijawa-web/src:/var/www/html
  #   expose:
  #     - "9000"
  #   networks:
  #     - infra_net
  #   restart: always

  # mysql:
  #   image: mysql:8
  #   container_name: mysql_db
  #   networks:
  #     - infra_net

  # phpmyadmin:
  #   image: phpmyadmin
  #   container_name: phpmyadmin
  #   networks:
  #     - infra_net

  # minio:
  #   image: minio/minio
  #   container_name: minio_s3
  #   networks:
  #     - infra_net

  # nagios:
  #   container_name: nagios_monitor
  #   networks:
  #     - infra_net
